export const PORTFOLIO_SECTORS = [
  { id: 'all', nameAr: 'جميع القطاعات', nameEn: 'ALL', iconName: 'Grid' },
  { id: 'medical', nameAr: 'القطاع الطبي', nameEn: 'MEDICAL SECTOR', iconName: 'Stethoscope' },
  { id: 'factories', nameAr: 'قطاع المصانع', nameEn: 'FACTORIES SECTOR', iconName: 'Factory' },
  { id: 'hospitality', nameAr: 'القطاع الفندقي', nameEn: 'HOSPITALITY SECTOR', iconName: 'Hotel' },
  { id: 'restaurants', nameAr: 'المطاعم والمأكولات', nameEn: 'RESTAURANTS & CULINARY', iconName: 'Utensils' },
  { id: 'food_products', nameAr: 'المنتجات الغذائية', nameEn: 'FOOD PRODUCTS', iconName: 'ShoppingBag' },
  { id: 'jewelry', nameAr: 'المجوهرات والألماس', nameEn: 'JEWELRY & DIAMONDS', iconName: 'Gem' },
  { id: 'fashion', nameAr: 'الفاشون والأزياء', nameEn: 'FASHION & APPAREL', iconName: 'Shirt' },
  { id: 'real_estate', nameAr: 'التطوير العقاري', nameEn: 'REAL ESTATE', iconName: 'Building' },
];

export const INITIAL_PROJECTS = [
  {
    id: 'proj_parent_choc_restaurant',
    titleAr: 'إنتاج استديو صابر الرئيسي',
    titleEn: 'Saber Studio Master Production',
    subtitleAr: 'تنسيق الأطعمة وحملة إعلانية تجارية',
    subtitleEn: 'Food Styling & Commercial Campaign',
    descriptionAr: 'حملة رئيسية شاملة تغطي تصوير المكان، ومنيو معزول بالكامل بخلفية بيضاء، وتصوير إعلاني فاخر للحلويات والشوكولاتة، مع تغطية فيديوهات ريلز للكواليس.',
    descriptionEn: 'Major parent campaign featuring full venue coverage, white background menu catalog, luxury chocolate marketing shoot, and behind-the-scenes reels.',
    coverImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop',
    ],
    clientName: 'La Chocolatier Group',
    date: 'June 2026',
    mainCategory: 'restaurants',
    sectorId: 'restaurants',
    tags: ['food photography', 'studio', 'product shots', 'food styling', 'reels'],
    projectType: 'parent',
    featured: true,
    photosCount: 82,
    reelsCount: 12,
    shootingDays: 5,
  },
  {
    id: 'proj_sub_choc_macro',
    titleAr: 'تصوير فوتوغرافي فاخر للشوكولاتة',
    titleEn: 'Luxury Chocolate Macro & Styling',
    descriptionAr: 'لقطات ماكرو فاخرة للشوكولاتة والحلويات بإضاءة استديو احترافية.',
    descriptionEn: 'Premium macro shots of chocolates and confections with professional studio lighting.',
    coverImage: 'https://images.unsplash.com/photo-1549007994-cb924ebd0a09?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1549007994-cb924ebd0a09?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1481391319762-47dff72954d9?q=80&w=800&auto=format&fit=crop',
    ],
    clientName: 'La Chocolatier Group',
    date: 'May 2026',
    mainCategory: 'food_products',
    sectorId: 'food_products',
    tags: ['food photography', 'macro', 'product shots', 'white background'],
    projectType: 'standalone',
    featured: true,
    photosCount: 24,
    reelsCount: 2,
    shootingDays: 2,
  },
  {
    id: 'proj_hospitality_resort',
    titleAr: 'منتجع شاطئ البحر الأحمر الفاخر',
    titleEn: 'Luxury Red Sea Beach Resort',
    descriptionAr: 'تغطية تصويرية شاملة لمنتجع سياحي فاخر على شاطئ البحر الأحمر.',
    descriptionEn: 'Comprehensive visual coverage of a luxury tourist resort on the Red Sea.',
    coverImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=800&auto=format&fit=crop',
    ],
    clientName: 'Red Sea Hotels',
    date: 'April 2026',
    mainCategory: 'hospitality',
    sectorId: 'hospitality',
    tags: ['lifestyle', 'campaign', 'studio'],
    projectType: 'standalone',
    featured: true,
    photosCount: 45,
    reelsCount: 6,
    shootingDays: 3,
  },
  {
    id: 'proj_jewelry_diamonds',
    titleAr: 'تصوير مجوهرات وألماس ملكي',
    titleEn: 'Royal Diamond & High Jewelry Macro',
    descriptionAr: 'لقطات ماكرو فائقة الدقة لمجوهرات وألماس فاخرة.',
    descriptionEn: 'Ultra high-resolution macro photography for luxury jewelry and diamonds.',
    coverImage: 'https://images.unsplash.com/photo-1515562141589-67f0d569b986?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1515562141589-67f0d569b986?q=80&w=800&auto=format&fit=crop',
    ],
    clientName: 'Royal Diamonds',
    date: 'March 2026',
    mainCategory: 'jewelry',
    sectorId: 'jewelry',
    tags: ['macro', 'product shots', 'white background', 'studio'],
    projectType: 'standalone',
    featured: true,
    photosCount: 30,
    reelsCount: 3,
    shootingDays: 2,
  },
  {
    id: 'proj_fashion_summer',
    titleAr: 'كولكشن الصيف - 25 طقم',
    titleEn: 'Summer Collection Lookbook 25 Outfits',
    descriptionAr: 'تصوير أزياء لكولكشن الصيف يضم 25 طقم مع موديلز احترافية.',
    descriptionEn: 'Fashion photography for summer collection featuring 25 outfits with professional models.',
    coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=800&auto=format&fit=crop',
    ],
    clientName: 'Fashion House',
    date: 'February 2026',
    mainCategory: 'fashion',
    sectorId: 'fashion',
    tags: ['lifestyle', 'campaign', 'studio'],
    projectType: 'standalone',
    featured: true,
    photosCount: 60,
    reelsCount: 8,
    shootingDays: 4,
  },
  {
    id: 'proj_clinic_reels',
    titleAr: 'جولة عيادة أسنان وجلدية',
    titleEn: 'Dental & Dermatology Clinic Tour',
    descriptionAr: 'جولة تصويرية لعيادة أسنان وجلدية مع ريلز كواليس.',
    descriptionEn: 'Clinic tour photography and videography for dental and dermatology practice.',
    coverImage: 'https://images.unsplash.com/photo-1629909615184-74f495363b67?q=80&w=800&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1629909615184-74f495363b67?q=80&w=800&auto=format&fit=crop',
    ],
    clientName: 'Smile Clinic',
    date: 'January 2026',
    mainCategory: 'medical',
    sectorId: 'medical',
    tags: ['behind the scenes', 'reels', 'lifestyle'],
    projectType: 'standalone',
    featured: true,
    photosCount: 20,
    reelsCount: 4,
    shootingDays: 1,
  },
];
